version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    networks:
      - sift
    ports:
      - "5672:5672"
      - "15672:15672"
    tty: true
    restart: unless-stopped
  gateway:
    build: ./gateway
    networks:
      - sift
    depends_on:
      - rabbitmq
    environment:
      - "SPRING_RABBITMQ_HOST=rabbitmq"
    ports:
      - "9090:8080"
    tty: true
    restart: unless-stopped
# Testing networking. Only making a container accessible by the gateway
#  nginx:
#    image: nginx:latest
#    network_mode: service:gateway
#    tty: true
#    restart: unless-stopped
networks:
  sift:
    driver: bridge