version: '3.7'
services:
  broker:
    image: rabbitmq:management-alpine
    networks:
      - sift
    ports:
      - "5672:5672"
      - "15672:15672"
    tty: true
    restart: unless-stopped
  database:
    image: postgres:15-alpine
    networks:
      - sift
    environment:
      - "POSTGRES_PASSWORD=dev"
    ports:
      - "5432:5432"
    tty: true
    restart: unless-stopped
  gateway:
    build: ./gateway
    networks:
      - sift
    depends_on:
      - broker
      - database
    environment:
      - "SPRING_RABBITMQ_HOST=rabbitmq"
    ports:
      - "9090:8080"
    tty: true
    restart: unless-stopped
  discord:
    build: ./discord
    networks:
      - sift
    depends_on:
      - gateway
    environment:
      - "SPRING_RABBITMQ_HOST=rabbitmq"
    tty: true
    restart: unless-stopped
  forex:
    build: ./forex
    networks:
      - sift
    depends_on:
      - gateway
    environment:
      - "SPRING_RABBITMQ_HOST=rabbitmq"
    tty: true
    restart: unless-stopped
  ledger:
    build: ./ledger
    networks:
      - sift
    depends_on:
      - gateway
    environment:
      - "SPRING_RABBITMQ_HOST=rabbitmq"
    tty: true
    restart: unless-stopped
networks:
  sift:
    driver: bridge