version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:management-alpine
    networks:
      - sift
    ports:
      - "5672:5672"
      - "15672:15672"
    tty: true
    restart: unless-stopped
  sift-core:
    build: ./sift
    networks:
      - sift
    depends_on:
      - rabbitmq
    environment:
      - "SPRING_RABBITMQ_HOST=rabbitmq"
    ports:
      - "8080:8080"
    tty: true
    restart: unless-stopped
  sift-gateway:
    build: ./gateway
    networks:
      - sift
    depends_on:
      - rabbitmq
    environment:
      - "SPRING_RABBITMQ_HOST=rabbitmq"
    ports:
      - "9090:8080"
    tty: true
    restart: unless-stopped
networks:
  sift:
    driver: bridge